[package]
name = "uefi-test-runner"
version = "0.2.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
uefi = { path = "..", features = ['exts'] }
uefi-services = { path = "../uefi-services" }

log = { version = "0.4.11", default-features = false }

qemu-exit = "2.0.0"

[features]
qemu = ["uefi-services/qemu"]
