[package]
name = "uefi-test-runner"
version = "0.2.0"
authors = ["The Rust OSDev team"]
publish = false
edition = "2021"
default-run = "uefi-test-runner"

[dependencies]
uefi = { path = "../uefi", features = ["alloc", "logger"] }
uefi-raw = { path = "../uefi-raw" }

log.workspace = true
ptr_meta = { workspace = true, optional = true }
qemu-exit = "3.0.0"

# TODO
[target.'cfg(target_os = "uefi")'.dependencies]
uefi-services = { path = "../uefi-services" }

[features]
# Enable the debug support protocol test.
debug_support = []

# Enable the multiprocessor test. This only works if KVM is enabled.
multi_processor = []

# Build for the host with a stub UEFI implementation instead of a real
# UEFI target.
native = ["dep:ptr_meta"]

# Enable the PXE test.
pxe = []

# Enable the `unstable` feature of the `uefi` crate.
unstable = ["uefi/unstable"]

# Enable the TPM v1 test.
tpm_v1 = []

# Enable the TPM v2 test.
tpm_v2 = []
