[workspace]
members = [
    "template",
    "uefi-macros",
    "uefi-services",
    "uefi-test-runner",
    "xtask",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[patch.crates-io]
uefi-macros = { path = "uefi-macros" }
uefi = { path = "uefi" }
