[package]
name = "xtask"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
command-run = { version = "1.0", default-features = false }
structopt = { version = "0.3", default-features = false }
strum = { version = "0.21", features = ["derive"] }
