name: Rust

on:
  push:
    branches:
      - main
      - version-*
  pull_request:
    branches:
      - main
      - version-*
  schedule:
    - cron:  '0 0 * * 0-6'

jobs:
  windows1:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows2:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows3:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows4:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows5:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows6:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows7:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows8:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows9:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10

  windows10:
    name: Check that the build works on a Windows target
    runs-on: windows-latest
    steps:
      - name: Install QEMU
        run: choco install qemu
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run VM tests
        run: cargo xtask run --target x86_64 --ci
        timeout-minutes: 10
