name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0-6'

jobs:
  build:
    name: Build on AArch64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rust-src
      # TODO: cache Rust binaries

    - name: Build
      run: cargo xtask --target aarch64 build

  build_and_test:
    name: Build and run tests on x86_64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install qemu and OVMF
      run: |
        sudo apt-get update
        sudo apt-get install qemu-system-x86 ovmf -y

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rust-src
      # TODO: cache Rust binaries

    - name: Build
      run: cargo xtask build

    - name: Run VM tests
      run: cargo xtask run --headless --ci

  test:
    name: Run tests and documentation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: rust-src
            override: true

      - name: Run cargo test
        run: cargo xtask test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: rustfmt, clippy, rust-src
            override: true

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        run: cargo xtask clippy

      - name: Run cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: doc
